### PR TITLE
Feature/cm seeds

### PR DESCRIPTION
**Pull request by comkirk30**
Updated seeds and read me files.

### CODE REVIEW

**Review by besharpe5 — APPROVED** [review]
🌱  looks good!

**Comment by ThomBurt** [comment]
Looks good to me

**Review by ThomBurt — APPROVED** [review]
Looks good to me

**Review by jamoore4579 — APPROVED** [review]

**Comment by emilyadarr** [comment]
Looks good!

**Review by emilyadarr — APPROVED** [review]

**Pull request merged**
